//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timur._0000
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ffffEntities : DbContext
    {
        public ffffEntities()
            : base("name=ffffEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Заказы> Заказы { get; set; }
        public DbSet<Клиенты> Клиенты { get; set; }
        public DbSet<Отзывы> Отзывы { get; set; }
        public DbSet<Сервисбит> Сервисбит { get; set; }
        public DbSet<Сотрудники> Сотрудники { get; set; }
        public DbSet<Услуги> Услуги { get; set; }
    }
}
