//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timur._0000
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int id { get; set; }
        public string цены { get; set; }
        public string качество { get; set; }
        public string гарантия { get; set; }
        public string возврат_заказа { get; set; }
        public int id_клиента { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
    }
}
