//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timur._0000
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public Клиенты()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int id { get; set; }
        public string иям { get; set; }
        public string фамилие { get; set; }
        public string отчество { get; set; }
        public string адрес { get; set; }
        public string номер { get; set; }
    
        public virtual ICollection<Заказы> Заказы { get; set; }
    }
}
