//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timur._0000
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сервисбит
    {
        public int id { get; set; }
        public string график_работы { get; set; }
        public string адрес { get; set; }
        public string почта { get; set; }
        public string номер { get; set; }
    }
}
