//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timur._0000
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги
    {
        public int id { get; set; }
        public string качество { get; set; }
        public string замена_терммопасты { get; set; }
        public string продувка { get; set; }
        public string обновление_версии { get; set; }
        public string очистка_компьютера { get; set; }
        public string дата { get; set; }
        public string время { get; set; }
    }
}
